// Fallback estático usado APENAS enquanto o hook `useSpecialties()` carrega
// o catálogo do banco (tabela `public.specialties`). Em runtime, os componentes
// devem consumir o hook — esta lista é a fonte legacy mantida só para evitar
// "flash" de select vazio na 1ª renderização.
//
// @deprecated Use `useSpecialties()` em src/hooks/useSpecialties.ts.
export const COMMON_SPECIALTIES_FALLBACK: string[] = [
  "Alergia e Imunologia",
  "Anestesiologia",
  "Angiologia",
  "Biomédico",
  "Cancerologia",
  "Cardiologia",
  "Cardiologia Pediátrica",
  "Cirurgia Bariátrica",
  "Cirurgia Buco Maxilo Facial",
  "Cirurgia Cardiovascular",
  "Cirurgia Cardíaca",
  "Cirurgia da Mão",
  "Cirurgia de Cabeça e Pescoço",
  "Cirurgia de Coluna",
  "Cirurgia do Aparelho Digestivo",
  "Cirurgia Endovascular",
  "Cirurgia Geral",
  "Cirurgia Oncológica",
  "Cirurgia Pediátrica",
  "Cirurgia Plástica",
  "Cirurgia Robótica",
  "Cirurgia Torácica",
  "Cirurgia Vascular",
  "Clínica Geral",
  "Clínica Médica",
  "Coloproctologia",
  "Comissão de PICC",
  "Dermatologia",
  "Eletrofisiologista Cardíaco",
  "Emergencista",
  "Endocrinologia",
  "Endocrinologia e Metabologia",
  "Endoscopia",
  "Endovascular",
  "Estimulação Cardíaca Artificial",
  "Fisiatra",
  "Fisioterapia",
  "Gastroenterologia",
  "Geriatria",
  "Ginecologia e Obstetrícia",
  "Grupo de Coluna",
  "Grupo de Coluna - Ortopedista",
  "Grupo de Dor",
  "Hematologia e Hemoterapia",
  "Hemodinâmica",
  "Hepatologia",
  "Infectologia",
  "Instrumentador Cirúrgico",
  "Mastologia",
  "Medicina Esportiva",
  "Medicina Física e Reabilitação",
  "Medicina Intensiva",
  "Medicina Nuclear",
  "Medicina Preventiva e Social",
  "Nefrologia",
  "Neurocirurgia",
  "Neurocirurgia Vascular",
  "Neurologia Clínica",
  "Neurologia Vascular",
  "Nutrologia",
  "Odontologia",
  "Oftalmologia",
  "Oncologia Clínica",
  "Ortopedia",
  "Ortopedia Pediátrica",
  "Ortopedia e Traumatologia",
  "Otorrinolaringologia",
  "Paliativismo e Terminalidade",
  "Pediatria",
  "Pneumologia",
  "Proctologia",
  "Radiologia e Diagnóstico por Imagem",
  "Radioterapia",
  "Reumatologia",
  "Terapia Intensiva",
  "Urologia",
];

/** @deprecated mantido para compatibilidade — use `useSpecialties()`. */
export const COMMON_SPECIALTIES = COMMON_SPECIALTIES_FALLBACK;
