// Lista comum de especialidades médicas — usada em selects multi nas Regras e Pagamentos.
// Pode ser estendida livremente: o componente aceita valores fora desta lista também.
export const COMMON_SPECIALTIES: string[] = [
  "Anestesiologia",
  "Cardiologia",
  "Cirurgia Geral",
  "Cirurgia Plástica",
  "Cirurgia Vascular",
  "Clínica Médica",
  "Dermatologia",
  "Endocrinologia",
  "Gastroenterologia",
  "Ginecologia e Obstetrícia",
  "Hematologia",
  "Hemodinâmica",
  "Infectologia",
  "Nefrologia",
  "Neurocirurgia",
  "Neurologia",
  "Oftalmologia",
  "Oncologia",
  "Ortopedia e Traumatologia",
  "Otorrinolaringologia",
  "Pediatria",
  "Pneumologia",
  "Psiquiatria",
  "Radiologia",
  "Reumatologia",
  "Urologia",
];