// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-payments.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_payments_default = defineTool({
  name: "list_payments",
  title: "Listar pagamentos",
  description: "Lista lotes de pagamento vis\xEDveis para o usu\xE1rio conectado, mais recentes primeiro. Aceita limite e filtro opcional por status.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("M\xE1ximo de lotes."),
    status: z.string().nullable().default(null).describe("Filtra por status exato (ex.: em_analise, aprovado, pago).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("payments").select("id, status, competence_month, created_at, hospital_id, gross_total, net_total").order("created_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { payments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-payment.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_payment_default = defineTool2({
  name: "get_payment",
  title: "Obter pagamento",
  description: "Retorna os dados principais de um lote de pagamento pelo id (UUID).",
  inputSchema: {
    id: z2.string().uuid().describe("UUID do lote de pagamento.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("payments").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Pagamento n\xE3o encontrado ou sem acesso." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { payment: data }
    };
  }
});

// src/lib/mcp/tools/list-pendencias.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_pendencias_default = defineTool3({
  name: "list_pendencias",
  title: "Listar pend\xEAncias",
  description: "Lista pend\xEAncias abertas vis\xEDveis para o usu\xE1rio, mais recentes primeiro.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("pendencias").select("id, kind, status, subject, created_at, assigned_to").neq("status", "resolved").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { pendencias: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool4({
  name: "whoami",
  title: "Quem sou eu",
  description: "Devolve o id, e-mail e claims do usu\xE1rio conectado via MCP. \xDAtil para conferir o v\xEDnculo.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bexwvmnwsbltrspmwusp";
var mcp_default = defineMcp({
  name: "exacta-mcp",
  title: "Exacta \u2014 Repasses m\xE9dicos",
  version: "0.1.0",
  instructions: "Ferramentas do Exacta (motor de concilia\xE7\xE3o de repasses m\xE9dicos). Use `list_payments` para ver lotes recentes, `get_payment` para detalhes de um lote espec\xEDfico, `list_pendencias` para itens abertos e `whoami` para confirmar o v\xEDnculo. Somente leitura.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_payments_default, get_payment_default, list_pendencias_default, whoami_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
