// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { ACTIVE_HOSPITAL_HEADER, getActiveHospitalId } from './activeHospital';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * Fetch com escopo de hospital.
 *
 * Anexa o header `x-active-hospital` em TODA requisição quando há hospital
 * ativo definido (ver activeHospital.ts). É o que ativa a RLS RESTRICTIVE
 * `active_hospital_scope` no banco. O valor é lido a cada chamada, então a
 * troca de hospital reflete imediatamente, sem recriar o client.
 */
const hospitalAwareFetch: typeof fetch = (input, init) => {
  const headers = new Headers(init?.headers ?? {});
  const hospitalId = getActiveHospitalId();
  if (hospitalId) {
    headers.set(ACTIVE_HOSPITAL_HEADER, hospitalId);
  } else {
    headers.delete(ACTIVE_HOSPITAL_HEADER);
  }
  return fetch(input, { ...init, headers });
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: hospitalAwareFetch,
  },
});
